name: nf-test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  nf-test:
    name: Run nf-test
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v3
        with:
          version: "24.10.5"

      - name: Install nf-test
        run: |
          curl -fsSL https://get.nf-test.com | bash
          sudo mv nf-test /usr/local/bin/

      - name: Run tests
        run: nf-test test --verbose
